POST http://localhost:8081/categorias HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJpYXppbmhhQGdtYWlsLmNvbSIsImV4cCI6MTY1MTE0MjczN30.ii4dIRJTkii_ZNWONG_UZ44dw97AebuzAxUPuBHJhDoxamaPEOovJfoIw8cXDb7j6rxScuSOU_Jx9Aj_IHv_tw

{
    "nome": "lalala1"
}
