@URL=http://localhost:8080


###
POST {{URL}}/clientes
Content-Type: application/json

{
  "nome": "Carin abdul",
  "email": "carinab@email.com",
  "cpfOuCnpj": "41852535000178Xssdw",
  "tipo": 2,
  "telefone1": "999987644",
  "telefone2": "9283737362",
  "logradouro": "rua das bromelias",
  "numero": "343",
  "complemento": "Apto 302",
  "cep": "37530000",
  "cidadeId": 2
}