@URL=http://localhost:8080


###
POST {{URL}}/clientes
Content-Type: application/json

{
  "nome": "Carin abdul lima",
  "email": "carinabdullima@email.com",
  "cpfOuCnpj": "52639890085",
  "tipo": 1,
  "telefone1": "999987640",
  "telefone2": "9283737361",
  "logradouro": "rua das cameliad",
  "numero": "340",
  "complemento": "Apto 12",
  "cep": "37530000",
  "cidadeId": 2
}