###
GET http://localhost:8080/clientes HTTP/1.1
Host: localhost:8080

###
GET http://localhost:8080/clientes/page HTTP/1.1
Host: localhost:8080

###
GET http://localhost:8080/clientes/97 HTTP/1.1
Host: localhost:8080


###
DELETE http://localhost:8080/clientes/1 HTTP/1.1
Host: localhost:8080

###
PUT http://localhost:8080/clientes/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "nome": "Maria silva borges",
  "email": "maria@yahoo.com"
}