GET http://localhost:8081/pedidos/1 HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWlkZWNvc3RhQGdtYWlsLmNvbSIsImV4cCI6MTY0ODcyNDIyOH0.hWhWmct3ukS5xpq8_7-_A3hjztnzR4E6xDHTY0DLtUce66pP6ybyHXBX37A_2QuBbJRw7sbZ1CliTTpOxK53XQ