GET http://localhost:8081/pedidos/1 HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWlkZWNvc3RhQGdtYWlsLmNvbSIsImV4cCI6MTY1MTE0MjQxMX0.6Q5e6NsFNn8jhK9izpVozewJKrIxLm0Hi-U-AnbTReIvvc3MsR80AshVKEM_tlI_hj4Du3tgFFuiVnol064DnQ