GET http://localhost:8081/pedidos/1 HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWlkZWNvc3RhQGdtYWlsLmNvbSIsImV4cCI6MTY0OTMyNjI2NH0.jmDfmBS62Rf9_4mnfBwGQx2PgyH4KCQw_qL2pRqtQsUuZlHM33aF-o857FgT5kIZBIED-RbSmhfKqohJBDxSrA