@URL=http://localhost:8081
POST {{URL}}/auth/refresh_token
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWlkZWNvc3RhQGdtYWlsLmNvbSIsImV4cCI6MTY1NTU2OTE2NH0.LgeJH1cD-nihYvE4brLQo3vCP7i8dFn88kyPgV9x42Q4LPYcvmsIeGeC-E1NyMoK2-BJjw_I4tsWmfW_gfRMzQ